[2024-11-20T10:46:02.031+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_flow.transform_wikipedia_data manual__2024-11-20T10:45:17.501375+00:00 [queued]>
[2024-11-20T10:46:02.035+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_flow.transform_wikipedia_data manual__2024-11-20T10:45:17.501375+00:00 [queued]>
[2024-11-20T10:46:02.035+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-11-20T10:46:02.040+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): transform_wikipedia_data> on 2024-11-20 10:45:17.501375+00:00
[2024-11-20T10:46:02.042+0000] {standard_task_runner.py:57} INFO - Started process 1093 to run task
[2024-11-20T10:46:02.045+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_flow', 'transform_wikipedia_data', 'manual__2024-11-20T10:45:17.501375+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia.py', '--cfg-path', '/tmp/tmp8f4ri4kx']
[2024-11-20T10:46:02.046+0000] {standard_task_runner.py:85} INFO - Job 22: Subtask transform_wikipedia_data
[2024-11-20T10:46:02.072+0000] {task_command.py:415} INFO - Running <TaskInstance: wikipedia_flow.transform_wikipedia_data manual__2024-11-20T10:45:17.501375+00:00 [running]> on host scheduler
[2024-11-20T10:46:02.181+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ClarkSon Tech' AIRFLOW_CTX_DAG_ID='wikipedia_flow' AIRFLOW_CTX_TASK_ID='transform_wikipedia_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-20T10:45:17.501375+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-20T10:45:17.501375+00:00'
[2024-11-20T10:46:03.201+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff7ecca160>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Rungrado+1st+of+May+Stadium%2C+North+Korea&format=json&limit=1
[2024-11-20T10:46:04.212+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff79ab2340>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Rungrado+1st+of+May+Stadium%2C+North+Korea&format=json&limit=1
[2024-11-20T10:46:05.228+0000] {logging_mixin.py:151} INFO - Error geocoding Rungrado 1st of May Stadium, North Korea: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Rungrado+1st+of+May+Stadium%2C+North+Korea&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff79ab2160>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:46:06.240+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff79ab2eb0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Michigan+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:46:07.258+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799d50d0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Michigan+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:46:08.273+0000] {logging_mixin.py:151} INFO - Error geocoding Michigan Stadium, United States: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Michigan+Stadium%2C+United+States&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799d5280>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:46:09.292+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff7d1efcd0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Ohio+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:46:10.307+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff7d1ef760>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Ohio+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:46:11.328+0000] {logging_mixin.py:151} INFO - Error geocoding Ohio Stadium, United States: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Ohio+Stadium%2C+United+States&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff60bdebe0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:46:12.346+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff79ab2a90>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Melbourne+Cricket+Ground%2C+Australia&format=json&limit=1
[2024-11-20T10:46:13.358+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff79ab26a0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Melbourne+Cricket+Ground%2C+Australia&format=json&limit=1
[2024-11-20T10:46:14.373+0000] {logging_mixin.py:151} INFO - Error geocoding Melbourne Cricket Ground, Australia: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Melbourne+Cricket+Ground%2C+Australia&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff79ab2160>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:46:15.384+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799d5c70>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Camp+Nou%2C+Spain&format=json&limit=1
[2024-11-20T10:46:16.396+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799d5e50>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Camp+Nou%2C+Spain&format=json&limit=1
[2024-11-20T10:46:17.413+0000] {logging_mixin.py:151} INFO - Error geocoding Camp Nou, Spain: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Camp+Nou%2C+Spain&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799d5fa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:46:18.433+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799e4a30>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Estadio+Azteca%2C+Mexico&format=json&limit=1
[2024-11-20T10:46:19.474+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff7f7a1100>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Estadio+Azteca%2C+Mexico&format=json&limit=1
[2024-11-20T10:46:20.488+0000] {logging_mixin.py:151} INFO - Error geocoding Estadio Azteca, Mexico: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Estadio+Azteca%2C+Mexico&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff7f784ee0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:46:21.500+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff79ab2c10>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=FNB+Stadium%2C+South+Africa&format=json&limit=1
[2024-11-20T10:46:22.511+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff79ab2f10>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=FNB+Stadium%2C+South+Africa&format=json&limit=1
[2024-11-20T10:46:23.520+0000] {logging_mixin.py:151} INFO - Error geocoding FNB Stadium, South Africa: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=FNB+Stadium%2C+South+Africa&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff7eb73580>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:46:24.532+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799e4c70>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=New+Administrative+Capital+Stadium%2C+Egypt&format=json&limit=1
[2024-11-20T10:46:25.542+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799e4e50>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=New+Administrative+Capital+Stadium%2C+Egypt&format=json&limit=1
[2024-11-20T10:46:26.553+0000] {logging_mixin.py:151} INFO - Error geocoding New Administrative Capital Stadium, Egypt: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=New+Administrative+Capital+Stadium%2C+Egypt&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799e4fa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:46:27.564+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799e8a30>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Rose+Bowl+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:46:28.576+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799e8c10>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Rose+Bowl+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:46:29.586+0000] {logging_mixin.py:151} INFO - Error geocoding Rose Bowl Stadium, United States: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Rose+Bowl+Stadium%2C+United+States&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799e8dc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:46:30.599+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799e84f0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Cotton+Bowl+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:46:31.616+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799e8730>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Cotton+Bowl+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:46:32.632+0000] {logging_mixin.py:151} INFO - Error geocoding Cotton Bowl Stadium, United States: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Cotton+Bowl+Stadium%2C+United+States&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799e8670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:46:33.650+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff60bde610>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Wembley+Stadium%2C+England&format=json&limit=1
[2024-11-20T10:46:34.661+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff60bde3a0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Wembley+Stadium%2C+England&format=json&limit=1
[2024-11-20T10:46:35.674+0000] {logging_mixin.py:151} INFO - Error geocoding Wembley Stadium, England: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Wembley+Stadium%2C+England&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff7d1ef760>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:46:36.693+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff79ab2850>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Lusail+Stadium%2C+Qatar&format=json&limit=1
[2024-11-20T10:46:37.703+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff79ab2d90>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Lusail+Stadium%2C+Qatar&format=json&limit=1
[2024-11-20T10:46:38.720+0000] {logging_mixin.py:151} INFO - Error geocoding Lusail Stadium, Qatar: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Lusail+Stadium%2C+Qatar&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff79ab21f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:46:39.740+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799ed550>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Bukit+Jalil+National+Stadium%2C+Malaysia&format=json&limit=1
[2024-11-20T10:46:40.755+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799ed730>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Bukit+Jalil+National+Stadium%2C+Malaysia&format=json&limit=1
[2024-11-20T10:46:41.767+0000] {logging_mixin.py:151} INFO - Error geocoding Bukit Jalil National Stadium, Malaysia: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Bukit+Jalil+National+Stadium%2C+Malaysia&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff7eced5b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:46:42.778+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff79ab2d00>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Borg+el-Arab+Stadium%2C+Egypt&format=json&limit=1
[2024-11-20T10:46:43.790+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff7d1efb50>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Borg+el-Arab+Stadium%2C+Egypt&format=json&limit=1
[2024-11-20T10:46:44.800+0000] {logging_mixin.py:151} INFO - Error geocoding Borg el-Arab Stadium, Egypt: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Borg+el-Arab+Stadium%2C+Egypt&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff7d1ef460>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:46:45.817+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799e4e80>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Estadio+Santiago+Bernab%C3%A9u%2C+Spain&format=json&limit=1
[2024-11-20T10:46:46.829+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799e8250>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Estadio+Santiago+Bernab%C3%A9u%2C+Spain&format=json&limit=1
[2024-11-20T10:46:47.847+0000] {logging_mixin.py:151} INFO - Error geocoding Estadio Santiago Bernabéu, Spain: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Estadio+Santiago+Bernab%C3%A9u%2C+Spain&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799e87f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:46:48.865+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799e83d0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Estadio+M%C3%A2s+Monumental%2C+Argentina&format=json&limit=1
[2024-11-20T10:46:49.880+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799e8d60>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Estadio+M%C3%A2s+Monumental%2C+Argentina&format=json&limit=1
[2024-11-20T10:46:50.900+0000] {logging_mixin.py:151} INFO - Error geocoding Estadio Mâs Monumental, Argentina: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Estadio+M%C3%A2s+Monumental%2C+Argentina&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799ed8e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:46:51.916+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799e89d0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Stadium+Australia%2C+Australia&format=json&limit=1
[2024-11-20T10:46:52.929+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799e8850>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Stadium+Australia%2C+Australia&format=json&limit=1
[2024-11-20T10:46:53.945+0000] {logging_mixin.py:151} INFO - Error geocoding Stadium Australia, Australia: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Stadium+Australia%2C+Australia&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799e89a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:46:54.960+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799e81c0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=MetLife+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:46:55.973+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799e4e20>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=MetLife+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:46:56.988+0000] {logging_mixin.py:151} INFO - Error geocoding MetLife Stadium, United States: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=MetLife+Stadium%2C+United+States&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799e4fd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:46:58.002+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff79ab2280>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Croke+Park%2C+Ireland&format=json&limit=1
[2024-11-20T10:46:59.011+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff79ab2a90>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Croke+Park%2C+Ireland&format=json&limit=1
[2024-11-20T10:47:00.029+0000] {logging_mixin.py:151} INFO - Error geocoding Croke Park, Ireland: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Croke+Park%2C+Ireland&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff79ab2b20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:47:01.048+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799f3220>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Jakarta+International+Stadium%2C+Indonesia&format=json&limit=1
[2024-11-20T10:47:02.061+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799f3400>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Jakarta+International+Stadium%2C+Indonesia&format=json&limit=1
[2024-11-20T10:47:03.074+0000] {logging_mixin.py:151} INFO - Error geocoding Jakarta International Stadium, Indonesia: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Jakarta+International+Stadium%2C+Indonesia&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799f35b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:47:04.087+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff60bde730>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Lambeau+Field%2C+United+States&format=json&limit=1
[2024-11-20T10:47:05.100+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799e4b80>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Lambeau+Field%2C+United+States&format=json&limit=1
[2024-11-20T10:47:06.115+0000] {logging_mixin.py:151} INFO - Error geocoding Lambeau Field, United States: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Lambeau+Field%2C+United+States&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799e4070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:47:07.129+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799e8190>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Signal+Iduna+Park%2C+Germany&format=json&limit=1
[2024-11-20T10:47:08.144+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799e8100>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Signal+Iduna+Park%2C+Germany&format=json&limit=1
[2024-11-20T10:47:09.154+0000] {logging_mixin.py:151} INFO - Error geocoding Signal Iduna Park, Germany: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Signal+Iduna+Park%2C+Germany&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799e8790>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:47:10.166+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799eddc0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Stade+de+France%2C+France&format=json&limit=1
[2024-11-20T10:47:11.179+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799edbb0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Stade+de+France%2C+France&format=json&limit=1
[2024-11-20T10:47:12.192+0000] {logging_mixin.py:151} INFO - Error geocoding Stade de France, France: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Stade+de+France%2C+France&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799ed0a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:47:13.205+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799e8d60>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Grand+Sports+Arena+of+the+Luzhniki+Olympic+Complex%2C+Russia&format=json&limit=1
[2024-11-20T10:47:14.216+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799e83d0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Grand+Sports+Arena+of+the+Luzhniki+Olympic+Complex%2C+Russia&format=json&limit=1
[2024-11-20T10:47:15.224+0000] {logging_mixin.py:151} INFO - Error geocoding Grand Sports Arena of the Luzhniki Olympic Complex, Russia: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Grand+Sports+Arena+of+the+Luzhniki+Olympic+Complex%2C+Russia&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799e8070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:47:16.237+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff7d1ef130>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Shah+Alam+Stadium%2C+Malaysia&format=json&limit=1
[2024-11-20T10:47:17.250+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff7d1efb50>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Shah+Alam+Stadium%2C+Malaysia&format=json&limit=1
[2024-11-20T10:47:18.260+0000] {logging_mixin.py:151} INFO - Error geocoding Shah Alam Stadium, Malaysia: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Shah+Alam+Stadium%2C+Malaysia&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff60bde4c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:47:19.276+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799edf40>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Estadio+Monumental%2C+Peru&format=json&limit=1
[2024-11-20T10:47:20.291+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799ed970>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Estadio+Monumental%2C+Peru&format=json&limit=1
[2024-11-20T10:47:21.304+0000] {logging_mixin.py:151} INFO - Error geocoding Estadio Monumental, Peru: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Estadio+Monumental%2C+Peru&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799ed550>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:47:22.320+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff79ab2d00>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Stadio+Giuseppe+Meazza%2C+Italy&format=json&limit=1
[2024-11-20T10:47:23.338+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff79ab2d60>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Stadio+Giuseppe+Meazza%2C+Italy&format=json&limit=1
[2024-11-20T10:47:24.363+0000] {logging_mixin.py:151} INFO - Error geocoding Stadio Giuseppe Meazza, Italy: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Stadio+Giuseppe+Meazza%2C+Italy&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff79ab22b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:47:25.379+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799ed8e0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Guangdong+Olympic+Stadium%2C+China&format=json&limit=1
[2024-11-20T10:47:26.390+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799ed550>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Guangdong+Olympic+Stadium%2C+China&format=json&limit=1
[2024-11-20T10:47:27.406+0000] {logging_mixin.py:151} INFO - Error geocoding Guangdong Olympic Stadium, China: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Guangdong+Olympic+Stadium%2C+China&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799edca0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:47:28.422+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff7d1efd30>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Hangzhou+Olympic+Sports+Expo+Centre+Stadium%2C+China&format=json&limit=1
[2024-11-20T10:47:29.438+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff7d1ef790>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Hangzhou+Olympic+Sports+Expo+Centre+Stadium%2C+China&format=json&limit=1
[2024-11-20T10:47:30.456+0000] {logging_mixin.py:151} INFO - Error geocoding Hangzhou Olympic Sports Expo Centre Stadium, China: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Hangzhou+Olympic+Sports+Expo+Centre+Stadium%2C+China&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799e8a00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:47:31.464+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799e8df0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=AT%26T+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:47:32.480+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799e8100>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=AT%26T+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:47:33.509+0000] {logging_mixin.py:151} INFO - Error geocoding AT&T Stadium, United States: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=AT%26T+Stadium%2C+United+States&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799e8370>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:47:34.524+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff79ab2670>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Stade+des+Martyrs%2C+DR+Congo&format=json&limit=1
[2024-11-20T10:47:35.541+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff79ab2040>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Stade+des+Martyrs%2C+DR+Congo&format=json&limit=1
[2024-11-20T10:47:36.556+0000] {logging_mixin.py:151} INFO - Error geocoding Stade des Martyrs, DR Congo: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Stade+des+Martyrs%2C+DR+Congo&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff799e8ca0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:49:02.849+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Est%C3%A1dio+Nacional+Man%C3%A9+Garrincha%2C+Brazil&format=json&limit=1
[2024-11-20T10:49:32.503+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=C%C3%ADvitas+Metropolitano%2C+Spain&format=json&limit=1
[2024-11-20T10:54:43.233+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Stadio+San+Nicola%2C+Italy&format=json&limit=1
[2024-11-20T10:55:05.251+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
[2024-11-20T10:55:05.257+0000] {process_utils.py:131} INFO - Sending 15 to group 1093. PIDs of all processes in the group: [1093]
[2024-11-20T10:55:05.258+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 1093
[2024-11-20T10:55:05.260+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-20T10:55:05.261+0000] {logging_mixin.py:151} INFO - Error geocoding La Bombonera, Argentina: Task received SIGTERM signal
[2024-11-20T10:55:07.835+0000] {taskinstance.py:1147} INFO - Dependencies not met for <TaskInstance: wikipedia_flow.transform_wikipedia_data manual__2024-11-20T10:45:17.501375+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2024-11-20T10:55:07.835+0000] {taskinstance.py:1147} INFO - Dependencies not met for <TaskInstance: wikipedia_flow.transform_wikipedia_data manual__2024-11-20T10:45:17.501375+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2024-11-20T10:55:07.836+0000] {local_task_job_runner.py:154} INFO - Task is not able to be run
