[2024-11-20T10:41:18.542+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_flow.transform_wikipedia_data manual__2024-11-20T10:41:14.291647+00:00 [queued]>
[2024-11-20T10:41:18.545+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_flow.transform_wikipedia_data manual__2024-11-20T10:41:14.291647+00:00 [queued]>
[2024-11-20T10:41:18.545+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-11-20T10:41:18.551+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): transform_wikipedia_data> on 2024-11-20 10:41:14.291647+00:00
[2024-11-20T10:41:18.553+0000] {standard_task_runner.py:57} INFO - Started process 982 to run task
[2024-11-20T10:41:18.555+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_flow', 'transform_wikipedia_data', 'manual__2024-11-20T10:41:14.291647+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia.py', '--cfg-path', '/tmp/tmpcbmj0kxi']
[2024-11-20T10:41:18.556+0000] {standard_task_runner.py:85} INFO - Job 19: Subtask transform_wikipedia_data
[2024-11-20T10:41:18.580+0000] {task_command.py:415} INFO - Running <TaskInstance: wikipedia_flow.transform_wikipedia_data manual__2024-11-20T10:41:14.291647+00:00 [running]> on host scheduler
[2024-11-20T10:41:18.684+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ClarkSon Tech' AIRFLOW_CTX_DAG_ID='wikipedia_flow' AIRFLOW_CTX_TASK_ID='transform_wikipedia_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-20T10:41:14.291647+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-20T10:41:14.291647+00:00'
[2024-11-20T10:41:20.034+0000] {base.py:396} INFO - Received an HTTP error (403): <html>
<head>
<title>Access blocked</title>
</head>
<body>
<h1>Access blocked</h1>

<p>You have been blocked because you have violated the
<a href="https://operations.osmfoundation.org/policies/nominatim/">usage policy</a>
of OSM's Nominatim geocoding service. Please be aware that OSM's resources are
limited and shared between many users. The usage policy is there to ensure that
the service remains usable for everybody.</p>

<p>Please review the terms and make sure that your
software adheres to the terms. You should in particular verify that you have set a
<b>custom HTTP referrer or HTTP user agent</b> that identifies your application, and
that you are not overusing the service with massive bulk requests.</p>

<p>If you feel that this block is unjustified or remains after you have adopted
your usage, you may contact the Nominatim system administrator at
nominatim@openstreetmap.org to have this block lifted.</p>
</body>
</head>

[2024-11-20T10:41:20.036+0000] {logging_mixin.py:151} INFO - Error geocoding Rungrado 1st of May Stadium, North Korea: Non-successful status code 403
[2024-11-20T10:41:21.752+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Michigan+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:41:23.388+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Michigan+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:41:25.034+0000] {logging_mixin.py:151} INFO - Error geocoding Michigan Stadium, United States: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Michigan+Stadium%2C+United+States&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
[2024-11-20T10:41:26.778+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Ohio+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:41:28.528+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Ohio+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:41:30.354+0000] {logging_mixin.py:151} INFO - Error geocoding Ohio Stadium, United States: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Ohio+Stadium%2C+United+States&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
[2024-11-20T10:41:32.099+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Melbourne+Cricket+Ground%2C+Australia&format=json&limit=1
[2024-11-20T10:41:33.843+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Melbourne+Cricket+Ground%2C+Australia&format=json&limit=1
[2024-11-20T10:41:35.683+0000] {logging_mixin.py:151} INFO - Error geocoding Melbourne Cricket Ground, Australia: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Melbourne+Cricket+Ground%2C+Australia&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
[2024-11-20T10:41:37.435+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Camp+Nou%2C+Spain&format=json&limit=1
[2024-11-20T10:41:39.171+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Camp+Nou%2C+Spain&format=json&limit=1
[2024-11-20T10:41:40.412+0000] {base.py:396} INFO - Received an HTTP error (503): <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>

[2024-11-20T10:41:40.414+0000] {logging_mixin.py:151} INFO - Geocoding timed out for Camp Nou, Spain. Retrying...
[2024-11-20T10:41:42.254+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Camp+Nou%2C+Spain&format=json&limit=1
[2024-11-20T10:41:43.484+0000] {base.py:396} INFO - Received an HTTP error (503): <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>

[2024-11-20T10:41:43.485+0000] {logging_mixin.py:151} INFO - Geocoding timed out for Camp Nou, Spain. Retrying...
[2024-11-20T10:41:45.311+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Camp+Nou%2C+Spain&format=json&limit=1
[2024-11-20T10:41:46.452+0000] {base.py:396} INFO - Received an HTTP error (503): <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>

[2024-11-20T10:41:46.455+0000] {logging_mixin.py:151} INFO - Geocoding timed out for Camp Nou, Spain. Retrying...
[2024-11-20T10:41:48.286+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Camp+Nou%2C+Spain&format=json&limit=1
[2024-11-20T10:41:49.525+0000] {base.py:396} INFO - Received an HTTP error (503): <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>

[2024-11-20T10:41:49.526+0000] {logging_mixin.py:151} INFO - Geocoding timed out for Camp Nou, Spain. Retrying...
[2024-11-20T10:41:51.355+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Camp+Nou%2C+Spain&format=json&limit=1
[2024-11-20T10:41:52.596+0000] {base.py:396} INFO - Received an HTTP error (503): <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>

[2024-11-20T10:41:52.598+0000] {logging_mixin.py:151} INFO - Geocoding timed out for Camp Nou, Spain. Retrying...
[2024-11-20T10:41:54.372+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Camp+Nou%2C+Spain&format=json&limit=1
[2024-11-20T10:41:55.470+0000] {base.py:396} INFO - Received an HTTP error (503): <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>

[2024-11-20T10:41:55.471+0000] {logging_mixin.py:151} INFO - Geocoding timed out for Camp Nou, Spain. Retrying...
[2024-11-20T10:41:57.187+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Camp+Nou%2C+Spain&format=json&limit=1
[2024-11-20T10:41:58.331+0000] {base.py:396} INFO - Received an HTTP error (503): <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>

[2024-11-20T10:41:58.334+0000] {logging_mixin.py:151} INFO - Geocoding timed out for Camp Nou, Spain. Retrying...
[2024-11-20T10:41:59.968+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Camp+Nou%2C+Spain&format=json&limit=1
[2024-11-20T10:42:01.197+0000] {base.py:396} INFO - Received an HTTP error (503): <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>

[2024-11-20T10:42:01.200+0000] {logging_mixin.py:151} INFO - Geocoding timed out for Camp Nou, Spain. Retrying...
[2024-11-20T10:42:02.829+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Camp+Nou%2C+Spain&format=json&limit=1
[2024-11-20T10:42:03.860+0000] {base.py:396} INFO - Received an HTTP error (503): <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>

[2024-11-20T10:42:03.862+0000] {logging_mixin.py:151} INFO - Geocoding timed out for Camp Nou, Spain. Retrying...
[2024-11-20T10:42:04.895+0000] {base.py:396} INFO - Received an HTTP error (503): <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>

[2024-11-20T10:42:04.896+0000] {logging_mixin.py:151} INFO - Geocoding timed out for Camp Nou, Spain. Retrying...
[2024-11-20T10:42:06.713+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Camp+Nou%2C+Spain&format=json&limit=1
[2024-11-20T10:42:07.750+0000] {base.py:396} INFO - Received an HTTP error (503): <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>

[2024-11-20T10:42:07.751+0000] {logging_mixin.py:151} INFO - Geocoding timed out for Camp Nou, Spain. Retrying...
[2024-11-20T10:42:09.478+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Camp+Nou%2C+Spain&format=json&limit=1
[2024-11-20T10:42:10.531+0000] {base.py:396} INFO - Received an HTTP error (503): <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>

[2024-11-20T10:42:10.532+0000] {logging_mixin.py:151} INFO - Geocoding timed out for Camp Nou, Spain. Retrying...
[2024-11-20T10:42:12.240+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Camp+Nou%2C+Spain&format=json&limit=1
[2024-11-20T10:42:13.338+0000] {base.py:396} INFO - Received an HTTP error (503): <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>

[2024-11-20T10:42:13.339+0000] {logging_mixin.py:151} INFO - Geocoding timed out for Camp Nou, Spain. Retrying...
[2024-11-20T10:42:15.106+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Camp+Nou%2C+Spain&format=json&limit=1
[2024-11-20T10:42:16.041+0000] {base.py:396} INFO - Received an HTTP error (503): <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>

[2024-11-20T10:42:16.042+0000] {logging_mixin.py:151} INFO - Geocoding timed out for Camp Nou, Spain. Retrying...
[2024-11-20T10:42:16.977+0000] {base.py:396} INFO - Received an HTTP error (503): <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>

[2024-11-20T10:42:16.978+0000] {logging_mixin.py:151} INFO - Geocoding timed out for Camp Nou, Spain. Retrying...
[2024-11-20T10:42:18.612+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Camp+Nou%2C+Spain&format=json&limit=1
[2024-11-20T10:42:19.542+0000] {base.py:396} INFO - Received an HTTP error (503): <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>

[2024-11-20T10:42:19.542+0000] {logging_mixin.py:151} INFO - Geocoding timed out for Camp Nou, Spain. Retrying...
[2024-11-20T10:42:21.246+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Camp+Nou%2C+Spain&format=json&limit=1
[2024-11-20T10:42:22.188+0000] {base.py:396} INFO - Received an HTTP error (503): <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>

[2024-11-20T10:42:22.190+0000] {logging_mixin.py:151} INFO - Geocoding timed out for Camp Nou, Spain. Retrying...
[2024-11-20T10:42:23.816+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Camp+Nou%2C+Spain&format=json&limit=1
[2024-11-20T10:42:24.852+0000] {base.py:396} INFO - Received an HTTP error (503): <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>

[2024-11-20T10:42:24.854+0000] {logging_mixin.py:151} INFO - Geocoding timed out for Camp Nou, Spain. Retrying...
[2024-11-20T10:42:25.785+0000] {base.py:396} INFO - Received an HTTP error (503): <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>

[2024-11-20T10:42:25.786+0000] {logging_mixin.py:151} INFO - Geocoding timed out for Camp Nou, Spain. Retrying...
[2024-11-20T10:42:27.413+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Camp+Nou%2C+Spain&format=json&limit=1
[2024-11-20T10:42:28.541+0000] {base.py:396} INFO - Received an HTTP error (503): <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>

[2024-11-20T10:42:28.542+0000] {logging_mixin.py:151} INFO - Geocoding timed out for Camp Nou, Spain. Retrying...
[2024-11-20T10:42:29.947+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Camp+Nou%2C+Spain&format=json&limit=1
[2024-11-20T10:42:30.963+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9056a1f0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Camp+Nou%2C+Spain&format=json&limit=1
[2024-11-20T10:42:31.978+0000] {logging_mixin.py:151} INFO - Error geocoding Camp Nou, Spain: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Camp+Nou%2C+Spain&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9056a3d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:42:32.991+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9056ae80>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Estadio+Azteca%2C+Mexico&format=json&limit=1
[2024-11-20T10:42:34.004+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff905740a0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Estadio+Azteca%2C+Mexico&format=json&limit=1
[2024-11-20T10:42:35.022+0000] {logging_mixin.py:151} INFO - Error geocoding Estadio Azteca, Mexico: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Estadio+Azteca%2C+Mexico&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90574280>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:42:36.034+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90574d30>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=FNB+Stadium%2C+South+Africa&format=json&limit=1
[2024-11-20T10:42:37.045+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90574f10>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=FNB+Stadium%2C+South+Africa&format=json&limit=1
[2024-11-20T10:42:38.056+0000] {logging_mixin.py:151} INFO - Error geocoding FNB Stadium, South Africa: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=FNB+Stadium%2C+South+Africa&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90581130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:42:39.070+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff905627f0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=New+Administrative+Capital+Stadium%2C+Egypt&format=json&limit=1
[2024-11-20T10:42:40.081+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90562880>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=New+Administrative+Capital+Stadium%2C+Egypt&format=json&limit=1
[2024-11-20T10:42:41.100+0000] {logging_mixin.py:151} INFO - Error geocoding New Administrative Capital Stadium, Egypt: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=New+Administrative+Capital+Stadium%2C+Egypt&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90562fd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:42:42.121+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9056a5e0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Rose+Bowl+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:42:43.138+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9056a2e0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Rose+Bowl+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:42:44.153+0000] {logging_mixin.py:151} INFO - Error geocoding Rose Bowl Stadium, United States: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Rose+Bowl+Stadium%2C+United+States&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9056a310>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:42:45.163+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90581bb0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Cotton+Bowl+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:42:46.178+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90581d90>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Cotton+Bowl+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:42:47.194+0000] {logging_mixin.py:151} INFO - Error geocoding Cotton Bowl Stadium, United States: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Cotton+Bowl+Stadium%2C+United+States&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90581f40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:42:48.214+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90581b20>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Wembley+Stadium%2C+England&format=json&limit=1
[2024-11-20T10:42:49.231+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90581a90>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Wembley+Stadium%2C+England&format=json&limit=1
[2024-11-20T10:42:50.245+0000] {logging_mixin.py:151} INFO - Error geocoding Wembley Stadium, England: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Wembley+Stadium%2C+England&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff905816d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:42:51.263+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9056a5b0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Lusail+Stadium%2C+Qatar&format=json&limit=1
[2024-11-20T10:42:52.280+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9056a910>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Lusail+Stadium%2C+Qatar&format=json&limit=1
[2024-11-20T10:42:53.296+0000] {logging_mixin.py:151} INFO - Error geocoding Lusail Stadium, Qatar: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Lusail+Stadium%2C+Qatar&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9056ac70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:42:54.307+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90562d90>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Bukit+Jalil+National+Stadium%2C+Malaysia&format=json&limit=1
[2024-11-20T10:42:55.323+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90562970>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Bukit+Jalil+National+Stadium%2C+Malaysia&format=json&limit=1
[2024-11-20T10:42:56.334+0000] {logging_mixin.py:151} INFO - Error geocoding Bukit Jalil National Stadium, Malaysia: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Bukit+Jalil+National+Stadium%2C+Malaysia&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff905626d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:42:57.355+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff905909d0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Borg+el-Arab+Stadium%2C+Egypt&format=json&limit=1
[2024-11-20T10:42:58.379+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90562f40>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Borg+el-Arab+Stadium%2C+Egypt&format=json&limit=1
[2024-11-20T10:42:59.395+0000] {logging_mixin.py:151} INFO - Error geocoding Borg el-Arab Stadium, Egypt: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Borg+el-Arab+Stadium%2C+Egypt&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90562760>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:43:00.411+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9056abe0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Estadio+Santiago+Bernab%C3%A9u%2C+Spain&format=json&limit=1
[2024-11-20T10:43:01.419+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9056aa60>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Estadio+Santiago+Bernab%C3%A9u%2C+Spain&format=json&limit=1
[2024-11-20T10:43:02.438+0000] {logging_mixin.py:151} INFO - Error geocoding Estadio Santiago Bernabéu, Spain: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Estadio+Santiago+Bernab%C3%A9u%2C+Spain&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9056a9a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:43:03.462+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90581370>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Estadio+M%C3%A2s+Monumental%2C+Argentina&format=json&limit=1
[2024-11-20T10:43:04.480+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff905811f0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Estadio+M%C3%A2s+Monumental%2C+Argentina&format=json&limit=1
[2024-11-20T10:43:05.496+0000] {logging_mixin.py:151} INFO - Error geocoding Estadio Mâs Monumental, Argentina: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Estadio+M%C3%A2s+Monumental%2C+Argentina&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90581e80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:43:06.517+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff905904f0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Stadium+Australia%2C+Australia&format=json&limit=1
[2024-11-20T10:43:07.532+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90590be0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Stadium+Australia%2C+Australia&format=json&limit=1
[2024-11-20T10:43:08.554+0000] {logging_mixin.py:151} INFO - Error geocoding Stadium Australia, Australia: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Stadium+Australia%2C+Australia&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90590d90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:43:09.575+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff905816d0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=MetLife+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:43:10.587+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90581fa0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=MetLife+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:43:11.597+0000] {logging_mixin.py:151} INFO - Error geocoding MetLife Stadium, United States: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=MetLife+Stadium%2C+United+States&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90581a30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:43:12.614+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9056ad30>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Croke+Park%2C+Ireland&format=json&limit=1
[2024-11-20T10:43:13.624+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9056a1f0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Croke+Park%2C+Ireland&format=json&limit=1
[2024-11-20T10:43:14.639+0000] {logging_mixin.py:151} INFO - Error geocoding Croke Park, Ireland: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Croke+Park%2C+Ireland&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9056a190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:43:15.651+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90574070>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Jakarta+International+Stadium%2C+Indonesia&format=json&limit=1
[2024-11-20T10:43:16.664+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90562c10>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Jakarta+International+Stadium%2C+Indonesia&format=json&limit=1
[2024-11-20T10:43:17.678+0000] {logging_mixin.py:151} INFO - Error geocoding Jakarta International Stadium, Indonesia: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Jakarta+International+Stadium%2C+Indonesia&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff905627f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:43:18.689+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90599550>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Lambeau+Field%2C+United+States&format=json&limit=1
[2024-11-20T10:43:19.700+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90599730>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Lambeau+Field%2C+United+States&format=json&limit=1
[2024-11-20T10:43:20.712+0000] {logging_mixin.py:151} INFO - Error geocoding Lambeau Field, United States: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Lambeau+Field%2C+United+States&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff905627f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:43:21.724+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9056a5b0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Signal+Iduna+Park%2C+Germany&format=json&limit=1
[2024-11-20T10:43:22.737+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9056aaf0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Signal+Iduna+Park%2C+Germany&format=json&limit=1
[2024-11-20T10:43:23.749+0000] {logging_mixin.py:151} INFO - Error geocoding Signal Iduna Park, Germany: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Signal+Iduna+Park%2C+Germany&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9056a1f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:43:24.759+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90581f40>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Stade+de+France%2C+France&format=json&limit=1
[2024-11-20T10:43:25.769+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90581b50>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Stade+de+France%2C+France&format=json&limit=1
[2024-11-20T10:43:26.779+0000] {logging_mixin.py:151} INFO - Error geocoding Stade de France, France: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Stade+de+France%2C+France&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff905816d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:43:27.789+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90590130>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Grand+Sports+Arena+of+the+Luzhniki+Olympic+Complex%2C+Russia&format=json&limit=1
[2024-11-20T10:43:28.807+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90590580>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Grand+Sports+Arena+of+the+Luzhniki+Olympic+Complex%2C+Russia&format=json&limit=1
[2024-11-20T10:43:29.820+0000] {logging_mixin.py:151} INFO - Error geocoding Grand Sports Arena of the Luzhniki Olympic Complex, Russia: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Grand+Sports+Arena+of+the+Luzhniki+Olympic+Complex%2C+Russia&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff905990a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:43:30.831+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff905998e0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Shah+Alam+Stadium%2C+Malaysia&format=json&limit=1
[2024-11-20T10:43:31.844+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90590af0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Shah+Alam+Stadium%2C+Malaysia&format=json&limit=1
[2024-11-20T10:43:32.868+0000] {logging_mixin.py:151} INFO - Error geocoding Shah Alam Stadium, Malaysia: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Shah+Alam+Stadium%2C+Malaysia&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90590eb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:43:33.885+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90581af0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Estadio+Monumental%2C+Peru&format=json&limit=1
[2024-11-20T10:43:34.905+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90581970>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Estadio+Monumental%2C+Peru&format=json&limit=1
[2024-11-20T10:43:35.916+0000] {logging_mixin.py:151} INFO - Error geocoding Estadio Monumental, Peru: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Estadio+Monumental%2C+Peru&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff905813d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:43:36.935+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9056a2e0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Stadio+Giuseppe+Meazza%2C+Italy&format=json&limit=1
[2024-11-20T10:43:37.950+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9056aa90>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Stadio+Giuseppe+Meazza%2C+Italy&format=json&limit=1
[2024-11-20T10:43:38.959+0000] {logging_mixin.py:151} INFO - Error geocoding Stadio Giuseppe Meazza, Italy: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Stadio+Giuseppe+Meazza%2C+Italy&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9056a820>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:43:39.970+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9059e250>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Guangdong+Olympic+Stadium%2C+China&format=json&limit=1
[2024-11-20T10:43:40.981+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9059e430>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Guangdong+Olympic+Stadium%2C+China&format=json&limit=1
[2024-11-20T10:43:41.995+0000] {logging_mixin.py:151} INFO - Error geocoding Guangdong Olympic Stadium, China: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Guangdong+Olympic+Stadium%2C+China&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9059e5e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:43:43.017+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9056adc0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Hangzhou+Olympic+Sports+Expo+Centre+Stadium%2C+China&format=json&limit=1
[2024-11-20T10:43:44.030+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9056a610>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Hangzhou+Olympic+Sports+Expo+Centre+Stadium%2C+China&format=json&limit=1
[2024-11-20T10:43:45.045+0000] {logging_mixin.py:151} INFO - Error geocoding Hangzhou Olympic Sports Expo Centre Stadium, China: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Hangzhou+Olympic+Sports+Expo+Centre+Stadium%2C+China&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90581910>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:43:46.066+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff905817c0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=AT%26T+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:43:47.079+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90590cd0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=AT%26T+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:43:48.098+0000] {logging_mixin.py:151} INFO - Error geocoding AT&T Stadium, United States: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=AT%26T+Stadium%2C+United+States&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90590d90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:43:49.113+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90599880>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Stade+des+Martyrs%2C+DR+Congo&format=json&limit=1
[2024-11-20T10:43:50.131+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90599070>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Stade+des+Martyrs%2C+DR+Congo&format=json&limit=1
[2024-11-20T10:43:51.146+0000] {logging_mixin.py:151} INFO - Error geocoding Stade des Martyrs, DR Congo: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Stade+des+Martyrs%2C+DR+Congo&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9059e190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:43:52.164+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90599910>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Stade+Tata+Rapha%C3%ABl%2C+DR+Congo&format=json&limit=1
[2024-11-20T10:43:53.181+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90599ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Stade+Tata+Rapha%C3%ABl%2C+DR+Congo&format=json&limit=1
[2024-11-20T10:43:54.197+0000] {logging_mixin.py:151} INFO - Error geocoding Stade Tata Raphaël, DR Congo: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Stade+Tata+Rapha%C3%ABl%2C+DR+Congo&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90599d60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:43:55.212+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90581e80>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=National+Sports+Stadium%2C+Zimbabwe&format=json&limit=1
[2024-11-20T10:43:56.235+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90581760>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=National+Sports+Stadium%2C+Zimbabwe&format=json&limit=1
[2024-11-20T10:43:57.250+0000] {logging_mixin.py:151} INFO - Error geocoding National Sports Stadium, Zimbabwe: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=National+Sports+Stadium%2C+Zimbabwe&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90581460>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:43:58.270+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9056af10>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Moi+International+Sports+Centre%2C+Kenya&format=json&limit=1
[2024-11-20T10:43:59.288+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9056a220>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Moi+International+Sports+Centre%2C+Kenya&format=json&limit=1
[2024-11-20T10:44:00.308+0000] {logging_mixin.py:151} INFO - Error geocoding Moi International Sports Centre, Kenya: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Moi+International+Sports+Centre%2C+Kenya&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9056ae80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:44:01.334+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9059ef40>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Beijing+National+Stadium%2C+China&format=json&limit=1
[2024-11-20T10:44:02.360+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9052b160>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Beijing+National+Stadium%2C+China&format=json&limit=1
[2024-11-20T10:44:03.387+0000] {logging_mixin.py:151} INFO - Error geocoding Beijing National Stadium, China: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Beijing+National+Stadium%2C+China&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9052b310>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:44:04.410+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9059e2b0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Stade+L%C3%A9opold+S%C3%A9dar+Senghor%2C+Senegal&format=json&limit=1
[2024-11-20T10:44:05.424+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90599eb0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Stade+L%C3%A9opold+S%C3%A9dar+Senghor%2C+Senegal&format=json&limit=1
[2024-11-20T10:44:06.441+0000] {logging_mixin.py:151} INFO - Error geocoding Stade Léopold Sédar Senghor, Senegal: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Stade+L%C3%A9opold+S%C3%A9dar+Senghor%2C+Senegal&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90599e50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:44:07.457+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff905992e0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Maracan%C3%A3%2C+Brazil&format=json&limit=1
[2024-11-20T10:44:08.470+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff905991f0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Maracan%C3%A3%2C+Brazil&format=json&limit=1
[2024-11-20T10:44:09.483+0000] {logging_mixin.py:151} INFO - Error geocoding Maracanã, Brazil: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Maracan%C3%A3%2C+Brazil&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90590be0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:44:10.499+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90590730>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Los+Angeles+Memorial+Coliseum%2C+United+States&format=json&limit=1
[2024-11-20T10:44:11.516+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90590490>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Los+Angeles+Memorial+Coliseum%2C+United+States&format=json&limit=1
[2024-11-20T10:44:12.534+0000] {logging_mixin.py:151} INFO - Error geocoding Los Angeles Memorial Coliseum, United States: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Los+Angeles+Memorial+Coliseum%2C+United+States&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9056a5b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:44:13.554+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90581550>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Azadi+Stadium%2C+Iran&format=json&limit=1
[2024-11-20T10:44:14.575+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9056ac70>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Azadi+Stadium%2C+Iran&format=json&limit=1
[2024-11-20T10:44:15.587+0000] {logging_mixin.py:151} INFO - Error geocoding Azadi Stadium, Iran: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Azadi+Stadium%2C+Iran&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90590c40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:44:16.607+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90590580>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Stadion+Utama+Gelora+Bung+Karno%2C+Indonesia&format=json&limit=1
[2024-11-20T10:44:17.623+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90590df0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Stadion+Utama+Gelora+Bung+Karno%2C+Indonesia&format=json&limit=1
[2024-11-20T10:44:18.643+0000] {logging_mixin.py:151} INFO - Error geocoding Stadion Utama Gelora Bung Karno, Indonesia: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Stadion+Utama+Gelora+Bung+Karno%2C+Indonesia&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90599d60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:44:19.657+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90599d90>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Caesar%27s+Superdome%2C+United+States&format=json&limit=1
[2024-11-20T10:44:20.667+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90599e50>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Caesar%27s+Superdome%2C+United+States&format=json&limit=1
[2024-11-20T10:44:21.689+0000] {logging_mixin.py:151} INFO - Error geocoding Caesar's Superdome, United States: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Caesar%27s+Superdome%2C+United+States&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90599ee0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:44:22.704+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9059ee50>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Arrowhead+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:44:23.716+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90581c10>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Arrowhead+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:44:24.728+0000] {logging_mixin.py:151} INFO - Error geocoding Arrowhead Stadium, United States: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Arrowhead+Stadium%2C+United+States&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff905813a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:44:25.744+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9059ea00>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Empower+Field%2C+United+States&format=json&limit=1
[2024-11-20T10:44:26.754+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9059ed00>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Empower+Field%2C+United+States&format=json&limit=1
[2024-11-20T10:44:27.765+0000] {logging_mixin.py:151} INFO - Error geocoding Empower Field, United States: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Empower+Field%2C+United+States&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9059eac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:44:28.781+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90599280>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Atat%C3%BCrk+Olimpiyat+Stadyumu%2C+Turkey&format=json&limit=1
[2024-11-20T10:44:29.792+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff905997c0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Atat%C3%BCrk+Olimpiyat+Stadyumu%2C+Turkey&format=json&limit=1
[2024-11-20T10:44:30.800+0000] {logging_mixin.py:151} INFO - Error geocoding Atatürk Olimpiyat Stadyumu, Turkey: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Atat%C3%BCrk+Olimpiyat+Stadyumu%2C+Turkey&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90599370>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:44:31.811+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90590850>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Old+Trafford%2C+England&format=json&limit=1
[2024-11-20T10:44:32.820+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90590ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Old+Trafford%2C+England&format=json&limit=1
[2024-11-20T10:44:33.829+0000] {logging_mixin.py:151} INFO - Error geocoding Old Trafford, England: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Old+Trafford%2C+England&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff905907f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:44:34.840+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff905819d0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Allianz+Arena%2C+Germany&format=json&limit=1
[2024-11-20T10:44:35.852+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90581040>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Allianz+Arena%2C+Germany&format=json&limit=1
[2024-11-20T10:44:36.867+0000] {logging_mixin.py:151} INFO - Error geocoding Allianz Arena, Germany: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Allianz+Arena%2C+Germany&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90581250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:44:37.882+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff905996a0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Naghsh-e-Jahan+Stadium%2C+Iran&format=json&limit=1
[2024-11-20T10:44:38.894+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90599d00>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Naghsh-e-Jahan+Stadium%2C+Iran&format=json&limit=1
[2024-11-20T10:44:39.909+0000] {logging_mixin.py:151} INFO - Error geocoding Naghsh-e-Jahan Stadium, Iran: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Naghsh-e-Jahan+Stadium%2C+Iran&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90599100>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:44:40.928+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9059ea30>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Bank+of+America+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:44:41.952+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9059ed90>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Bank+of+America+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:44:42.968+0000] {logging_mixin.py:151} INFO - Error geocoding Bank of America Stadium, United States: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Bank+of+America+Stadium%2C+United+States&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9059ea00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:44:43.988+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff905901f0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Principality+Stadium%2C+Wales&format=json&limit=1
[2024-11-20T10:44:45.001+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff905901c0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Principality+Stadium%2C+Wales&format=json&limit=1
[2024-11-20T10:44:46.023+0000] {logging_mixin.py:151} INFO - Error geocoding Principality Stadium, Wales: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Principality+Stadium%2C+Wales&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90590880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:44:47.047+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90574a00>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Olympiastadion%2C+Germany&format=json&limit=1
[2024-11-20T10:44:48.062+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90590640>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Olympiastadion%2C+Germany&format=json&limit=1
[2024-11-20T10:44:49.071+0000] {logging_mixin.py:151} INFO - Error geocoding Olympiastadion, Germany: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Olympiastadion%2C+Germany&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90590250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:44:50.084+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9059e160>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Cairo+International+Stadium%2C+Egypt&format=json&limit=1
[2024-11-20T10:44:51.094+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9059ea00>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Cairo+International+Stadium%2C+Egypt&format=json&limit=1
[2024-11-20T10:44:52.105+0000] {logging_mixin.py:151} INFO - Error geocoding Cairo International Stadium, Egypt: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Cairo+International+Stadium%2C+Egypt&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9059e430>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:44:53.126+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90599d60>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=FirstEnergy+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:44:54.136+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90599ca0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=FirstEnergy+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:44:55.154+0000] {logging_mixin.py:151} INFO - Error geocoding FirstEnergy Stadium, United States: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=FirstEnergy+Stadium%2C+United+States&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90599970>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:44:55.672+0000] {process_utils.py:131} INFO - Sending 15 to group 982. PIDs of all processes in the group: [982]
[2024-11-20T10:44:55.674+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 982
[2024-11-20T10:44:55.675+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-20T10:44:55.676+0000] {logging_mixin.py:151} INFO - Error geocoding Estádio Nacional Mané Garrincha, Brazil: Task received SIGTERM signal
[2024-11-20T10:44:56.694+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff905993d0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Stadio+Olimpico%2C+Italy&format=json&limit=1
[2024-11-20T10:44:57.713+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90574c10>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Stadio+Olimpico%2C+Italy&format=json&limit=1
[2024-11-20T10:44:58.728+0000] {logging_mixin.py:151} INFO - Error geocoding Stadio Olimpico, Italy: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Stadio+Olimpico%2C+Italy&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90574520>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:44:59.750+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff905992e0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Nissan+Stadium%2C+Japan&format=json&limit=1
[2024-11-20T10:45:00.765+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff905993a0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Nissan+Stadium%2C+Japan&format=json&limit=1
[2024-11-20T10:45:01.781+0000] {logging_mixin.py:151} INFO - Error geocoding Nissan Stadium, Japan: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Nissan+Stadium%2C+Japan&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90599a00>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:45:02.793+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90581940>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=NRG+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:45:03.811+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff905818b0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=NRG+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:45:04.828+0000] {logging_mixin.py:151} INFO - Error geocoding NRG Stadium, United States: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=NRG+Stadium%2C+United+States&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90581b20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:45:05.848+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9059e8e0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Shanghai+Stadium%2C+China&format=json&limit=1
[2024-11-20T10:45:06.858+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90574610>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Shanghai+Stadium%2C+China&format=json&limit=1
[2024-11-20T10:45:07.875+0000] {logging_mixin.py:151} INFO - Error geocoding Shanghai Stadium, China: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Shanghai+Stadium%2C+China&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff905748e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:45:08.895+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90574820>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=M%26T+Bank+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:45:09.906+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90590790>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=M%26T+Bank+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:45:10.918+0000] {logging_mixin.py:151} INFO - Error geocoding M&T Bank Stadium, United States: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=M%26T+Bank+Stadium%2C+United+States&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff905909d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:45:11.933+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9059ed60>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Mercedes-Benz+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:45:12.943+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90581490>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Mercedes-Benz+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:45:13.958+0000] {logging_mixin.py:151} INFO - Error geocoding Mercedes-Benz Stadium, United States: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Mercedes-Benz+Stadium%2C+United+States&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90581e20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:45:14.970+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9063cd60>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=C%C3%ADvitas+Metropolitano%2C+Spain&format=json&limit=1
[2024-11-20T10:45:15.977+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90599ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=C%C3%ADvitas+Metropolitano%2C+Spain&format=json&limit=1
[2024-11-20T10:45:16.988+0000] {logging_mixin.py:151} INFO - Error geocoding Cívitas Metropolitano, Spain: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=C%C3%ADvitas+Metropolitano%2C+Spain&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90599130>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:45:18.004+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90599b80>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Olympic+National+Sports+Complex+Stadium%2C+Ukraine&format=json&limit=1
[2024-11-20T10:45:19.015+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90599100>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Olympic+National+Sports+Complex+Stadium%2C+Ukraine&format=json&limit=1
[2024-11-20T10:45:20.033+0000] {logging_mixin.py:151} INFO - Error geocoding Olympic National Sports Complex Stadium, Ukraine: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Olympic+National+Sports+Complex+Stadium%2C+Ukraine&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff905902e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:45:21.050+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff905902e0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=SoFi+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:45:22.077+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff905909a0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=SoFi+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:45:23.097+0000] {logging_mixin.py:151} INFO - Error geocoding SoFi Stadium, United States: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=SoFi+Stadium%2C+United+States&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90599640>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:45:24.119+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90599160>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Seoul+Olympic+Stadium%2C+South+Korea&format=json&limit=1
[2024-11-20T10:45:25.135+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90599ee0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Seoul+Olympic+Stadium%2C+South+Korea&format=json&limit=1
[2024-11-20T10:45:26.159+0000] {logging_mixin.py:151} INFO - Error geocoding Seoul Olympic Stadium, South Korea: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Seoul+Olympic+Stadium%2C+South+Korea&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9063cf10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:45:27.184+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90581d90>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Bak%C4%B1+Olimpiya+stadionu%2C+Azerbaijan&format=json&limit=1
[2024-11-20T10:45:28.206+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff905815b0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Bak%C4%B1+Olimpiya+stadionu%2C+Azerbaijan&format=json&limit=1
[2024-11-20T10:45:29.222+0000] {logging_mixin.py:151} INFO - Error geocoding Bakı Olimpiya stadionu, Azerbaijan: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Bak%C4%B1+Olimpiya+stadionu%2C+Azerbaijan&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9059ef70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:45:30.237+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9064a280>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Olympic+Stadium%2C+Greece&format=json&limit=1
[2024-11-20T10:45:31.248+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9064a3d0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Olympic+Stadium%2C+Greece&format=json&limit=1
[2024-11-20T10:45:32.264+0000] {logging_mixin.py:151} INFO - Error geocoding Olympic Stadium, Greece: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Olympic+Stadium%2C+Greece&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9064a910>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:45:33.287+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9059e430>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Olympiastadion+M%C3%BCnchen%2C+Germany&format=json&limit=1
[2024-11-20T10:45:34.306+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9059e280>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Olympiastadion+M%C3%BCnchen%2C+Germany&format=json&limit=1
[2024-11-20T10:45:35.327+0000] {logging_mixin.py:151} INFO - Error geocoding Olympiastadion München, Germany: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Olympiastadion+M%C3%BCnchen%2C+Germany&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90581d90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:45:36.341+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90574940>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Lumen+Field%2C+United+States&format=json&limit=1
[2024-11-20T10:45:37.351+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9063ce80>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Lumen+Field%2C+United+States&format=json&limit=1
[2024-11-20T10:45:38.367+0000] {logging_mixin.py:151} INFO - Error geocoding Lumen Field, United States: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Lumen+Field%2C+United+States&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90709e80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:45:39.383+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9064ad00>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Estadio+Ol%C3%ADmpico+Universitario%2C+Mexico&format=json&limit=1
[2024-11-20T10:45:40.399+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9064ad90>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Estadio+Ol%C3%ADmpico+Universitario%2C+Mexico&format=json&limit=1
[2024-11-20T10:45:41.418+0000] {logging_mixin.py:151} INFO - Error geocoding Estadio Olímpico Universitario, Mexico: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Estadio+Ol%C3%ADmpico+Universitario%2C+Mexico&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90599850>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:45:42.441+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90599460>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Gillette+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:45:43.467+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90599280>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Gillette+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:45:44.482+0000] {logging_mixin.py:151} INFO - Error geocoding Gillette Stadium, United States: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Gillette+Stadium%2C+United+States&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90709850>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:45:45.498+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9064a3d0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=King+Abdullah+Sports+City+Stadium%2C+Saudi+Arabia&format=json&limit=1
[2024-11-20T10:45:46.522+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9064a730>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=King+Abdullah+Sports+City+Stadium%2C+Saudi+Arabia&format=json&limit=1
[2024-11-20T10:45:47.541+0000] {logging_mixin.py:151} INFO - Error geocoding King Abdullah Sports City Stadium, Saudi Arabia: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=King+Abdullah+Sports+City+Stadium%2C+Saudi+Arabia&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9064a820>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:45:48.565+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90581880>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Lincoln+Financial+Field%2C+United+States&format=json&limit=1
[2024-11-20T10:45:49.581+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90581bb0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Lincoln+Financial+Field%2C+United+States&format=json&limit=1
[2024-11-20T10:45:50.600+0000] {logging_mixin.py:151} INFO - Error geocoding Lincoln Financial Field, United States: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Lincoln+Financial+Field%2C+United+States&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90581c40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:45:51.615+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90599d00>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Levi%27s+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:45:52.624+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff905995e0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Levi%27s+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:45:53.635+0000] {logging_mixin.py:151} INFO - Error geocoding Levi's Stadium, United States: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Levi%27s+Stadium%2C+United+States&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff905901c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-11-20T10:45:54.647+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90590df0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Acrisure+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:45:55.657+0000] {connectionpool.py:871} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90599fd0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /search?q=Acrisure+Stadium%2C+United+States&format=json&limit=1
[2024-11-20T10:45:55.709+0000] {process_utils.py:149} WARNING - process psutil.Process(pid=982, name='airflow task runner: wikipedia_flow transform_wikipedia_data manual__2024-11-20T10:41:14.291647+00:00 19', status='sleeping', started='10:41:17') did not respond to SIGTERM. Trying SIGKILL
[2024-11-20T10:45:55.735+0000] {process_utils.py:86} INFO - Sending the signal 9 to group 982
[2024-11-20T10:45:55.750+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=982, name='airflow task runner: wikipedia_flow transform_wikipedia_data manual__2024-11-20T10:41:14.291647+00:00 19', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='10:41:17') (982) terminated with exit code -9
[2024-11-20T10:45:55.752+0000] {standard_task_runner.py:172} ERROR - Job 19 was killed before it finished (likely due to running out of memory)
